
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";


export const metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
