
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";
import MarquePage from "@/components/Marquee";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <MarquePage></MarquePage>

        {children}
        <Footer></Footer>
        <Toaster />
      </body>
    </html>
  );
}
